server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: microservice-barberos
          uri: ${URI_BARBEROS:http://localhost:8082}
          predicates:
            - Path=/barberos/**
          filters:
            - StripPrefix=1
        - id: microservice-servicios
          uri: ${URI_SERVICIOS:http://localhost:8083}
          predicates:
            - Path=/servicios/**
          filters:
            - StripPrefix=1
        - id: microservice-reservas
          uri: ${URI_RESERVAS:http://localhost:8084}
          predicates:
            - Path=/reservas/**
          filters:
            - StripPrefix=1
        - id: microservice-reportes
          uri: ${URI_REPORTES:http://localhost:8085}
          predicates:
            - Path=/reportes/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/realms/barbershop}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
